allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  prisma: true
  unrs-resolver: true

overrides:
  '@hono/node-server': '^1.19.14'
  hono: '^4.12.25'
  multer: '^2.2.0'
  js-yaml: '^4.2.0'
  form-data: '^4.0.6'
